name: Build upstream

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout upstream repo
        run: |
          hash=$(cat version)
          git clone https://github.com/DorianRudolph/sirula.git --branch master && \
          cd sirula && \
          git checkout $hash

      - name: Build App
        run: |
          cd sirula && \
          sudo apt install -y libpango1.0-dev libatk1.0-dev libgtk-3-dev libgtk-layer-shell-dev && \
          cargo build --verbose
      
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sirula/target/release/sirula
          asset_name: sirula
          tag: ${{ github.ref }}
          overwrite: true
          body: "CI Release"
