name: Build upstream

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout upstream repo
        run: |
          hash=$(cat version)
          git clone https://github.com/DorianRudolph/sirula.git --branch master && \
          cd sirula && \
          git checkout $hash

      - name: Build App
        run: |
          cd sirula && \
          cargo build --verbose
